### ISSUE TITLE
Integrate thank you notification per email as cron job

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/infrastructure-modules-shared#30]
An starter code is to be found in branch `thankyou-cronjob` (the the script is missing since it has still secrets and should not be commited until we use vars and update the bucket) .

- [ ] In infrastructure-env-staging open a new module with the namespace `notifications` (this namespace will be useful for future feats)
- [ ] In order to use images it is much simpler just to containerize the app than using other alternatives as storage claim or whatever. Please use infrastructure-images for it. In the future we could integrate the script in notification-mail-service either as part of its job or as another package.
- [ ] Use env vars for the config
- [ ] update bucket secrets (@hugotiburtino)

**Comment by Entkenntnis** [comment]
no, this is not necessary anymore
