### ISSUE TITLE
first login with NBP account: investigate why undefined instead of UUID when clicking on "eigenes Profil"

### ISSUE THREAD

**Issue by AndreasHuber** [serlo/infrastructure-modules-shared#41]

**Comment by hugotiburtino** [comment]
fixed by #40

**Comment by AndreasHuber** [comment]
For documentation: We had found from the code example of https://www.ory.sh/docs/kratos/hooks/configure-hooks#trigger-precedence that the "general" hooks are only executed in case the "specific" hooks - like password in the example or oidc in our case - do not apply. To always have the hook be executed, we therefore had to copy it from the "general" hooks also to the oidc hooks.
