### ISSUE TITLE
Nginx error 413 "Request entity too large" on image upload

### ISSUE THREAD

**Issue by Knorrke** [serlo/infrastructure-modules-shared#5]
The uploaded file is 1,69 MB big, so it shouldn't be too big for the upload. This sounds like a configuration problem:
https://kittmedia.com/2013/nginx-fehler-413-request-entity-too-large/

**Comment by inyono** [comment]
Finally fixed. The limit can be configured via an [annotation on the ingress resource](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size).

Also: `truncate -s 2M foo.txt` creates a file with the specified size for testing purposes.
